{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-1.0.0.jar",
          "url": "utils-1.0.0.jar",
          "size": 918,
          "sha512": "4a549ae644d0aa21dc425174cbc171b67c9f1f727988a60552b105f130de0269d5190efce383c50fe36e18d1f6a559da97e284060d08e933517bd6fe06328e29",
          "sha256": "064f8f2a9403dd2c367332a59ef3e7264323c4f7856122f2e74d1b6f55cc298e",
          "sha1": "8ac6598ad773e321c0a8be8ebb296996b99c65bd",
          "md5": "8bee17aaf52763a08ba84b0ff9f500fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-1.0.0.jar",
          "url": "utils-1.0.0.jar",
          "size": 918,
          "sha512": "4a549ae644d0aa21dc425174cbc171b67c9f1f727988a60552b105f130de0269d5190efce383c50fe36e18d1f6a559da97e284060d08e933517bd6fe06328e29",
          "sha256": "064f8f2a9403dd2c367332a59ef3e7264323c4f7856122f2e74d1b6f55cc298e",
          "sha1": "8ac6598ad773e321c0a8be8ebb296996b99c65bd",
          "md5": "8bee17aaf52763a08ba84b0ff9f500fc"
        }
      ]
    }
  ]
}
