{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.3.jar",
          "url": "tkms-java-utils-1.0.3.jar",
          "size": 42148,
          "sha512": "33d89d0d8e142d57a4c80bfd60582c5539e905e16a40ccc974f255265e08ff326929efa6ab543c4bbc4fad94b8dc9fca0be0dcf44379f766c6b9108445c04a5a",
          "sha256": "3ee1ab426bd500cc2884d9286c5ce67533f61e0c42cb82c424f8ce39885333eb",
          "sha1": "2acea2fa47fe3fd9ee3de9a9473377bc2c7d0256",
          "md5": "646bc16b46e5c08bdc58ffbf7ec94c1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.3.jar",
          "url": "tkms-java-utils-1.0.3.jar",
          "size": 42148,
          "sha512": "33d89d0d8e142d57a4c80bfd60582c5539e905e16a40ccc974f255265e08ff326929efa6ab543c4bbc4fad94b8dc9fca0be0dcf44379f766c6b9108445c04a5a",
          "sha256": "3ee1ab426bd500cc2884d9286c5ce67533f61e0c42cb82c424f8ce39885333eb",
          "sha1": "2acea2fa47fe3fd9ee3de9a9473377bc2c7d0256",
          "md5": "646bc16b46e5c08bdc58ffbf7ec94c1e"
        }
      ]
    }
  ]
}
