{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.3.jar",
          "url": "tkms-java-utils-1.0.3.jar",
          "size": 42562,
          "sha512": "8df0babba139b1d6a17a589675cbb792647fdbbb367613f86cabb68566f0941d656de6f8e0714655d56d686facf934bd58ab4607a09714560a8f737ed271849f",
          "sha256": "fcfca56a4bc937acee7e1b8c58493a10cfe8475b4b989b2104326afa68dde460",
          "sha1": "7848c3b9e57a893674116e68090fc32ce1d3610f",
          "md5": "d4fbb57cfb9a691759b8f77e883ea233"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.3.jar",
          "url": "tkms-java-utils-1.0.3.jar",
          "size": 42562,
          "sha512": "8df0babba139b1d6a17a589675cbb792647fdbbb367613f86cabb68566f0941d656de6f8e0714655d56d686facf934bd58ab4607a09714560a8f737ed271849f",
          "sha256": "fcfca56a4bc937acee7e1b8c58493a10cfe8475b4b989b2104326afa68dde460",
          "sha1": "7848c3b9e57a893674116e68090fc32ce1d3610f",
          "md5": "d4fbb57cfb9a691759b8f77e883ea233"
        }
      ]
    }
  ]
}
