{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.0.jar",
          "url": "tkms-java-utils-1.0.0.jar",
          "size": 24047,
          "sha512": "95c375e7f0807cc79bc74769087cf0391d54b33dcc51552378f186d039819b67b36b213e952980bcb1244b3ad43dbca98a54033964eabde6b336d547ba992171",
          "sha256": "a8ae15f7815ee2d538ec6c46c82d1d74ddfefee390f52e0faed952eda6da8e9c",
          "sha1": "3d43c418f01f97d8b5837d5ebb2154d78605ca31",
          "md5": "05ca626f2b1c1e1ab24cdfedece154a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.0.jar",
          "url": "tkms-java-utils-1.0.0.jar",
          "size": 24047,
          "sha512": "95c375e7f0807cc79bc74769087cf0391d54b33dcc51552378f186d039819b67b36b213e952980bcb1244b3ad43dbca98a54033964eabde6b336d547ba992171",
          "sha256": "a8ae15f7815ee2d538ec6c46c82d1d74ddfefee390f52e0faed952eda6da8e9c",
          "sha1": "3d43c418f01f97d8b5837d5ebb2154d78605ca31",
          "md5": "05ca626f2b1c1e1ab24cdfedece154a8"
        }
      ]
    }
  ]
}
