{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.0.jar",
          "url": "tkms-java-utils-1.0.0.jar",
          "size": 12484,
          "sha512": "fdb3df026bc05903decb45789a1118011c3e1ca2985ea1d1cbf0dfa2fb07de472e086b22217b71ad5f7d317c46b6cb57dc45c285e06910dfd55118114c954c08",
          "sha256": "9080b755653d94a5a1f7b1c56af8abc231a974bffd0d67fc4f0e6c6a1fe4b912",
          "sha1": "7d84a2ac5d1b7a66556589855a903ad3b3936412",
          "md5": "d42bc60601f44b46e2f0097b42eaf23d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.0.jar",
          "url": "tkms-java-utils-1.0.0.jar",
          "size": 12484,
          "sha512": "fdb3df026bc05903decb45789a1118011c3e1ca2985ea1d1cbf0dfa2fb07de472e086b22217b71ad5f7d317c46b6cb57dc45c285e06910dfd55118114c954c08",
          "sha256": "9080b755653d94a5a1f7b1c56af8abc231a974bffd0d67fc4f0e6c6a1fe4b912",
          "sha1": "7d84a2ac5d1b7a66556589855a903ad3b3936412",
          "md5": "d42bc60601f44b46e2f0097b42eaf23d"
        }
      ]
    }
  ]
}
