{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.1.jar",
          "url": "tkms-java-utils-1.0.1.jar",
          "size": 30787,
          "sha512": "14578034ef9ff886e7de7e570cdaf9a63dac21850563d7a4af88d13c127087cbf8f85abeee03a8f04ca3e353d87b293cbfd0841ac1fe2830541b13ab662c6b17",
          "sha256": "ef9d38e9bb037bb2c032a8dbb5b6545c2155d7def9ecd012487dad497ca9b63c",
          "sha1": "9d27f2ab82d5437f2d76ee82a37973d2e04e2c14",
          "md5": "f19f7bdb0db31aa6efb3ad0d092b98c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.1.jar",
          "url": "tkms-java-utils-1.0.1.jar",
          "size": 30787,
          "sha512": "14578034ef9ff886e7de7e570cdaf9a63dac21850563d7a4af88d13c127087cbf8f85abeee03a8f04ca3e353d87b293cbfd0841ac1fe2830541b13ab662c6b17",
          "sha256": "ef9d38e9bb037bb2c032a8dbb5b6545c2155d7def9ecd012487dad497ca9b63c",
          "sha1": "9d27f2ab82d5437f2d76ee82a37973d2e04e2c14",
          "md5": "f19f7bdb0db31aa6efb3ad0d092b98c6"
        }
      ]
    }
  ]
}
