{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.1.jar",
          "url": "tkms-java-utils-1.0.1.jar",
          "size": 31603,
          "sha512": "60e5ddf0f5017a9d24f59c6f450fc89a5aca2bf8cc230537d930e64d22c808bff8bca833f0a914590f07e59d36806e66ebb02df85ffa7bb6f080535e5aeaa250",
          "sha256": "9525b21df9df3a5ad5a26e8769045ba5f8ad57076f5a6e5a1a986b457048ce4d",
          "sha1": "6671bbd4c1b6cfc6fa7fa12ef70b9eb113f037b8",
          "md5": "2567234351e16eeead4b07f950d1ff59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.1.jar",
          "url": "tkms-java-utils-1.0.1.jar",
          "size": 31603,
          "sha512": "60e5ddf0f5017a9d24f59c6f450fc89a5aca2bf8cc230537d930e64d22c808bff8bca833f0a914590f07e59d36806e66ebb02df85ffa7bb6f080535e5aeaa250",
          "sha256": "9525b21df9df3a5ad5a26e8769045ba5f8ad57076f5a6e5a1a986b457048ce4d",
          "sha1": "6671bbd4c1b6cfc6fa7fa12ef70b9eb113f037b8",
          "md5": "2567234351e16eeead4b07f950d1ff59"
        }
      ]
    }
  ]
}
