{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.1.jar",
          "url": "tkms-java-utils-1.0.1.jar",
          "size": 31600,
          "sha512": "8bd60ec75918582170db4244992c1006421d065ac4e44750f32c7b8a293600eb703214a6cfe6f1f536c7a8f87d40adb61c0634389e5293b3c4e9bd5dc90a4e2d",
          "sha256": "3ac7103963b09862bf47f329f797d6235cddfcdea878f79c9fdd9da8718e20fa",
          "sha1": "9740e41a754c6cf592f676e02eebda6134c00593",
          "md5": "00c2f061d041eb5f50bade4c8739b2dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.1.jar",
          "url": "tkms-java-utils-1.0.1.jar",
          "size": 31600,
          "sha512": "8bd60ec75918582170db4244992c1006421d065ac4e44750f32c7b8a293600eb703214a6cfe6f1f536c7a8f87d40adb61c0634389e5293b3c4e9bd5dc90a4e2d",
          "sha256": "3ac7103963b09862bf47f329f797d6235cddfcdea878f79c9fdd9da8718e20fa",
          "sha1": "9740e41a754c6cf592f676e02eebda6134c00593",
          "md5": "00c2f061d041eb5f50bade4c8739b2dd"
        }
      ]
    }
  ]
}
