{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.2.jar",
          "url": "tkms-java-utils-1.0.2.jar",
          "size": 37675,
          "sha512": "a40f5142239ac964c1ac258a9358375263b1079c66515f1920bf23313bc15b0537bc72c38b46f756b8d993af3147afe246a85e54c264057ba1c5a5792c7df040",
          "sha256": "34a7b9f1f4f873d1c6ea1bd9ee816e99cbe97cdb6159b584be0b9ad009b5002c",
          "sha1": "6c883f8300f9811e2ec102c357b124447daef06d",
          "md5": "213000331514a6654a6a5fc2be4f0c59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.2.jar",
          "url": "tkms-java-utils-1.0.2.jar",
          "size": 37675,
          "sha512": "a40f5142239ac964c1ac258a9358375263b1079c66515f1920bf23313bc15b0537bc72c38b46f756b8d993af3147afe246a85e54c264057ba1c5a5792c7df040",
          "sha256": "34a7b9f1f4f873d1c6ea1bd9ee816e99cbe97cdb6159b584be0b9ad009b5002c",
          "sha1": "6c883f8300f9811e2ec102c357b124447daef06d",
          "md5": "213000331514a6654a6a5fc2be4f0c59"
        }
      ]
    }
  ]
}
