{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tkms",
    "module": "tkms-java-utils",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.2.jar",
          "url": "tkms-java-utils-1.0.2.jar",
          "size": 34956,
          "sha512": "0d28e950394490497eb68c2abdc8cee5bfed8846b8f9e543845520d716610973c3c679ea90ae6cd0b04e75f67dddfbf429719932a873ddc0dd8bc49a47c50c72",
          "sha256": "4243d8d1dd7a2159073556a190ed5deac13bf69a712ec9d4b0f3528cd1866a0b",
          "sha1": "0af0997f1f829284cc204ebdc32069e3f201e33b",
          "md5": "ab8fd366aa56534304e7da77648826f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tkms-java-utils-1.0.2.jar",
          "url": "tkms-java-utils-1.0.2.jar",
          "size": 34956,
          "sha512": "0d28e950394490497eb68c2abdc8cee5bfed8846b8f9e543845520d716610973c3c679ea90ae6cd0b04e75f67dddfbf429719932a873ddc0dd8bc49a47c50c72",
          "sha256": "4243d8d1dd7a2159073556a190ed5deac13bf69a712ec9d4b0f3528cd1866a0b",
          "sha1": "0af0997f1f829284cc204ebdc32069e3f201e33b",
          "md5": "ab8fd366aa56534304e7da77648826f3"
        }
      ]
    }
  ]
}
